name: cipher
description: A Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  bloc: ^8.1.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_facebook_auth: ^5.0.6
  flutter_native_splash: ^2.2.16
  flutter_secure_storage: ^7.0.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.18.0
  jiffy: ^5.0.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  multi_select_flutter: ^4.1.3
  path_provider: ^2.0.12
  pinput: ^2.2.20
  responsive_framework: ^0.2.0
  textfield_tags: ^2.0.2
  url_launcher: ^6.1.8


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  lint: ^2.0.1
  mocktail: ^0.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/skills/
    - assets/banners/
    - assets/categories/
    - assets/services/
    - assets/bottomNavigationItems/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

