name: cipher
description: A Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dependencies:
    path: packages/dependencies

  flutter:
    sdk: flutter
  json_annotation: ^4.8.0



dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: ^2.0.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/skills/
    - assets/banners/
    - assets/categories/
    - assets/services/
    - assets/bottomNavigationItems/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

