name: cipher
description: A Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

# run command `dart pub global activate rps` to activate rps
scripts:
  # run command `rps` to run the flutter project
  run: "flutter run"
  # run command `rps gen` to generate code generated files
  gen: "flutter pub run build_runner build --delete-conflicting-outputs"
  # run commant `rps apk` to build apk
  apk: "flutter build apk --release"
  # run command `rps get` to get all dependencies
  get: "cd packages/dependencies && flutter pub get && cd .. && cd .. && flutter pub get"

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  bloc_concurrency: ^0.2.1
  dependencies:
    path: packages/dependencies
  encrypt: ^5.0.1

  flutter:
    sdk: flutter
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lint: ^2.0.1
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.12.0
  very_good_analysis: ^4.0.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/homaale.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/notification/
    - assets/skills/
    - assets/banners/
    - assets/categories/
    - assets/services/
    - assets/bottomNavigationItems/
    - assets/support/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
