// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-RruUbsZ9JmEV0GxPwYKRT28E_jLbCrw',
    appId: '1:245846975950:android:24347ec871768f149db79f',
    messagingSenderId: '245846975950',
    projectId: 'grand-eye-356710',
    storageBucket: 'grand-eye-356710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa18sGbuG_CN9DAq0soA-ucVrg2IBL3dc',
    appId: '1:245846975950:ios:ea42deefde243d449db79f',
    messagingSenderId: '245846975950',
    projectId: 'grand-eye-356710',
    storageBucket: 'grand-eye-356710.appspot.com',
    androidClientId: '245846975950-er0mh3lvr9j21getocpsfo6lk44lm9oh.apps.googleusercontent.com',
    iosClientId: '245846975950-4m4o50p5l22fjgo7mio82h65sdu2j45b.apps.googleusercontent.com',
    iosBundleId: 'com.cagtu.cipher',
  );
}
