name: dependencies
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  auto_size_text: ^3.0.0
  basic_utils: ^5.5.1
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.1
  bloc_test: ^9.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  equatable: ^2.0.5
  encrypt: ^5.0.1
  file_picker: ^5.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_facebook_auth: ^5.0.8
  flutter_native_splash: ^2.2.16
  flutter_secure_storage: ^8.0.0
  freezed_annotation: ^2.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  image_picker: ^0.8.7+3
  intl: ^0.18.0P
  jiffy: ^5.0.1
  json_annotation: ^4.8.0
  multi_select_flutter: ^4.1.3
  path_provider: ^2.0.12
  pinput: ^2.2.20
  responsive_framework: ^0.2.0
  textfield_tags: ^2.0.2
  url_launcher: ^6.1.8
  flutter_svg: ^2.0.3
  share_plus: ^6.3.1
  video_player: ^2.6.0
  chewie: ^1.4.0
  get_it: ^7.2.0
  table_calendar: ^3.0.9
  permission_handler: ^10.2.0
  telephony: ^0.2.0
  firebase_core: ^2.9.0
  card_loading: ^0.3.0
  connectivity_plus: ^3.0.3
  dropdown_search: ^5.0.6
  flutter_inappwebview: ^5.7.2+3
  flutter_html: ^3.0.0-alpha.6
  showcaseview: ^2.0.3
  stream_transform: ^2.1.0
  cloud_firestore: ^4.5.0
  tuple: ^2.0.1
  google_maps_flutter: ^2.2.5
  wechat_camera_picker: ^3.7.0
  wechat_assets_picker: ^8.4.2
  decimal: ^2.3.2
  geocoder2: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


