import 'package:cipher/core/constants/constants.dart';
import 'package:cipher/widgets/widgets.dart';
import 'package:flutter/material.dart';

class PasswordAndSecurity extends StatelessWidget {
  const PasswordAndSecurity({super.key});
  static const routeName = '/password-and-security';

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        kHeight50,
        CustomHeader(
          leadingWidget: IconButton(
            onPressed: () {
              Navigator.pop(context);
            },
            icon: const Icon(
              Icons.arrow_back,
            ),
          ),
          trailingWidget: IconButton(
            icon: const Icon(Icons.search),
            onPressed: () {},
          ),
          child: const Text(
            'Password & Security',
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w500,
              color: Color(
                0xff212529,
              ),
            ),
          ),
        ),
        const Divider(),
        kHeight20,
        const Text(
          'Password',
          style: kPurpleText16,
        ),
        kHeight5,
        const Text(
          'You will be asked to enter password before logging in Homaale',
          style: kHelper1,
        ),
        CustomElevatedButton(
          callback: () {},
          label: 'Change password',
        ),
        kHeight20,
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Text('Two Factor Authentication'),
            Switch(
              value: false,
              onChanged: (value) {},
            ),
          ],
        ),
        kHeight5,
        const Text(
          'Add an extra layer of security to block unauthorized access and protect your account.',
          style: kHelper1,
        ),
        kHeight20,
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Text('Authenticator App Code'),
            OutlinedButton(
              onPressed: () {},
              child: const Text(
                'Setup',
              ),
            ),
          ],
        ),
        kHeight5,
        const Text(
          "Enter a code generated by Google authenticator app to confirm it's you.",
          style: kHelper1,
        ),
        kHeight20,
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Text('SMS Recovery'),
            OutlinedButton(
              onPressed: () {},
              child: const Text(
                'Setup',
              ),
            ),
          ],
        ),
        kHeight5,
        const Text(
          "Recieve a four digit code by text message to confirm it's you",
          style: kHelper1,
        ),
        kHeight20,
        Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            const Text(
              'Security Question',
              style: kPurpleText16,
            ),
            Switch(
              value: false,
              onChanged: (value) {},
            ),
          ],
        ),
        kHeight5,
        const Text(
          "Answer a question you choose to confirm it's you.",
          style: kHelper1,
        ),
        kHeight50,
        CustomElevatedButton(
          callback: () {},
          label: 'Save',
        ),
      ],
    );
  }
}
